# Конфигурация Air для hot-reload
[build]
  bin = "./tmp/main"       # Путь к скомпилированному бинарному файлу
  cmd = "go build -o ./tmp/main ./cmd/server"
  exclude_dir = ["tmp"]

[log]
  level = "info"